#FORMATTING
name="sadvik"
age=18

print(f" iam {name} , my age is {age} ")

college="MRCET"
course="cse AIML"

print(f" my college is  {college}, and my course is  {course}")


print(f" iam {name} , my age is {age} ")

print("my name is",name , "my age is",age)

#its an example of usage of comma to print the two statenemts in one line 
name="bittu"
course="csm"
print(name,course)

#CONCATENATION

name="sadvik"
name1="yadav"
print(name + name1)
print(name+" "+name1)

name2=name1
print(name2 + name)
print(name2+" "+name)

